<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Coraza.Rendering</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Coraza.Core\Coraza.Core.csproj" />
    <ProjectReference Include="..\Coraza.Remoto\Coraza.Remoto.csproj" />
  </ItemGroup>

</Project>
